modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile="${mod_id}.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "ae2"
type="required"
versionRange = "[19.0.27,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId="glodium"
type="optional"
versionRange="[1.21-2.0-neoforge,)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="extendedae"
type="optional"
versionRange="[1.21-2.0-neoforge,)"
ordering="AFTER"
side="BOTH"